#!/bin/bash
#
# catchall - this shell script simply prints messages
# on receipt of signals. The signals QUIT,INT,HUP and TERM
# are identified specially. Others are identified as 'unknown
# signals'
#
# if catchall exits under its own control it prints a message.
#

trap onexit EXIT

trap gotquit QUIT
trap gotunkn 2 4 5 7 8 9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 

trap gotint INT
trap gothup HUP
trap gotterm TERM

gotterm() {
    echo "$progname: received signal TERM"
}

onexit() {
    echo "$progname: exiting..."
}

gotint() {
    echo "$progname: received signal INT"
}

gotquit () {
    echo "$progname: received signal QUIT"
}

gothup () {
    echo "$progname: received signal HUP"
}

gotunkn() {
    echo "$progname: received unknown signal"
}


typeset -i nsecs=5*60 i=0 incr=4
progname=$(basename $0)
echo "$progname: sleeping for $nsecs seconds. signal me to awaken."
while [ $i -lt $nsecs ]; do
    sleep $incr
    ((i+=incr))
done
#
exit 0



