#!/bin/bash
#  Program Name: handleArgs
#        Author: Devon McBride
#         Class: cs260 - Unix System Administration
#                MW 5:30 - 7:00
# Last Modified: 02/27/2004
#############################################################

line=`ls -l $1`
echo $line  # without an cmd line arg, it gets all visable files in dir
if [ $# -lt 1 ]; then
    echo
    echo -e "there are no args, so it handled all files in the dir (ls -l)"
fi
if [ $# -gt 1 ]; then
    while [ ! $# -lt 1 ]
    do
	echo `ls -l $1`
	shift
	if [ ! $# -gt 0 ]; then
	    exit 
        fi
    done
fi




#for each one, grab each one and put it into a variable...there are like 5...:
#=`echo $line | cut -d: -f1`
#groupID=`echo $line | cut -d: -f3`

# puts userIDs into a temporary file in this directory
#`echo $line | cut -d: -f4 | tr ',' '\n' | sort > temp`

##### awkwardly awks userID and @ccsf.edu with a terrible space between
##### and saves to temp again.  I then use sed to eliminate the space  
##### and finally save it to a file named for the crn.
#awk '{print $1, "@ccsf.edu"}' temp | sed 's/ //' > $crn 

###### counts addresses with numbers (those would be students, not teachers) 
#count=`grep -c [0-9] $crn`
