#!/bin/bash
#  Program Name: status
#        Author: Devon McBride
#         Class: cs260 - Unix System Administration
#                MW 5:30 - 7:00
# Last Modified: 02/29/2004
#
# USAGE: status MODE [file] [file] [file] etc...
#		 where MODE is -p, -s, -f with a file or list, or
#                      -l with time 
#

fatal() {
    # fatal - outputs a fatal error message to stderr and exits.
    #     Uses the function error() to output the error message.
    error $*
    exit 1
}

error() {
    # Outputs an error message to stderr.
    # Keeps track of whether errors have been seen.
    # SETS A GLOBAL VARIABLE errors_seen TO INDICATE AN ERROR HAS BEEN SEEN!
    typeset progname=$(basename $0)
    errors_seen=true
    echo -e "$progname: error: $*" >&2
	#echo "$progname: usage: $progname { -p | -s | -f } list-of-files" >&2
}

checkArgs() {
	# checkArgs tests to see if the first arguement is an acceptable mode. 
	# This function takes one arguement: the mode ($1).
    case "$1" in
        -p) fatal "The '-p' option is not yet available." ;;
        -s) fatal "The '-s' option is not yet available." ;;
        -f) mode="file" ;;
        -l)	fatal The -l option is not yet available. ;;
         *) fatal Option unknown or missing ;;
    esac
}

default_list() {
    # default_list outputs the default list of things to work on
	# if no files were given as arguements.  The default list consists
	# of a list of visable items in the current directory. 
    # It takes two arguments: the system ($1) and the type of things
    #                         status is requested on ($2). 
    # For assignment two, the only possibility for $2 is "file"
    #                             and $1 (system) doesn't matter
    typeset mode=$2 system=$1

    # whatever goes to standard output is command-substituted 
    # into the list
    ls
}

dofile() {
    # Generate status information for a single file on
    #    the indicated system
    # There are two arguments: $1 is the system; $2 is the file path
    # I'm putting them in local variables for you
    typeset system=$1 file=$2 

	# Check to see if the file currently being worked on exists.
	# If it doesn't exist, shift to get the next one and check it, too.
	if [ ! -d $file -a ! -e $file ]; then
		error $file isn't a valid file.  It doesn't seem to exist.

	# This is where it processes everything.
	else
		# Gets octal permissions if it's in Linux.
		if [ "$system" = "Linux" ]; then  
			typeset octalperms=`stat --format=%a $file`
		fi

		# Checks to see if the file is a directory.
		if [ -d $file ]; then
			typeset filetype_char="d"

			#Breaks up 'ls' into it's components (only for directories here)
			#See descriptive variables  here to see what's grabbed by awk and sed.
			typeset rawpermissions=`ls -dl $file | awk '{ print $1 ; }'`

			typeset username=`ls -dl $file | awk '{ print $3 ; }'`
			typeset groupname=`ls -dl $file | awk '{ print $4 ; }'`
			typeset filename=`ls -dl $file | awk '{ print $9 ; }'`  
			typeset uidnumeric=`ls -dln $file | awk '{ print $3 ; }'`
			typeset gidnumeric=`ls -dln $file | awk '{ print $4 ; }'`
			typeset sizeblocks=`ls -dls $file | awk '{ print $1 ; }'`

			# We want # of subdirectories in a directory, not the # of links.
			typeset numsubdirs=`ls -l $file | grep -c '^d.*'`
	
			# Weedles out the symbolic permissions.
			typeset symbolperms=`echo $rawpermissions | sed 's/^.//'`

		# Checks to see if the file is a device file
		elif [ -c $file ] || [ -b $file ]; then
			#Breaks up 'ls' into it's components (only for device files here)
			#See descriptive variables  here for what's grabbed by awk and sed.
			typeset rawpermissions=`ls -l $file | awk '{ print $1 ; }'`
			typeset links=`ls -l $file | awk '{ print $2 ; }'`
			typeset username=`ls -l $file | awk '{ print $3 ; }'`
			typeset groupname=`ls -l $file | awk '{ print $4 ; }'`
			typeset majordevnum=`ls -lL $file | awk '{ print $5 ; }'` 
			typeset minordevnum=`ls -lL $file | awk '{ print $6 ; }'`
			typeset filename=`ls -l $file | awk '{ print $10 ; }'`  
			typeset uidnumeric=`ls -ln $file | awk '{ print $3 ; }'`
			typeset gidnumeric=`ls -ln $file | awk '{ print $4 ; }'`
			typeset sizeblocks=`ls -ls $file | awk '{ print $1 ; }'`
	
			# Weedles out the type, and the symbolic permissions.
			typeset filetype_char=`echo $rawpermissions | sed 's/r.*$//'`
			typeset symbolperms=`echo $rawpermissions | sed 's/^.//'`

		else
			#Breaks up the 'ls' command into it's components
			#See descriptive variables  for what's grabbed by awk and sed.
			typeset rawpermissions=`ls -l $file | awk '{ print $1 ; }'`
			typeset links=`ls -l $file | awk '{ print $2 ; }'`
			typeset username=`ls -l $file | awk '{ print $3 ; }'`
			typeset groupname=`ls -l $file | awk '{ print $4 ; }'`
			typeset sizebytes=`ls -l $file | awk '{ print $5 ; }'` 
			typeset filename=`ls -l $file | awk '{ print $9 ; }'`  
			typeset uidnumeric=`ls -n $file | awk '{ print $3 ; }'`
			typeset gidnumeric=`ls -n $file | awk '{ print $4 ; }'`
			typeset sizeblocks=`ls -s $file | awk '{ print $1 ; }'`

			# Weedles out the type, and the symbolic permissions.
			typeset filetype_char=`echo $rawpermissions | sed 's/r.*$//'`
			typeset symbolperms=`echo $rawpermissions | sed 's/^.//'`
		fi

		# 'Expands' the file type character extracted earlier 
		# to be a user-friendly word. 
		case "$filetype_char" in
			-) typeset filetype="regular file" ;;
			b) typeset filetype="block special file" ;;
			c) typeset filetype="character special file" ;;
			d) typeset filetype="directory" ;;
			m) typeset filetype="XENIX shared data (memory)" ;;
			n) typeset filetype="network special file" ;;
			p) typeset filetype="fifo (named pipe)" ;;
			s) typeset filetype="XENIX semaphore (socket)" ;;
			l) typeset filetype="symbolic link" ;;
			*) error filetype not detected.  What to do? ;;
		esac

##############################################################################
##### To make the output look nice, I wanted to use the whole screen.    #####
##### So that makes the 'if' statements here look messy.                 #####           #####
##### OUTPUT TO STDOUT: depending on the type:                           #####
#####                                    directory, regular, or other    #####
##############################################################################
if [ "$filetype_char" = "d" ]; then

echo " -----------------------------------------------------------------------"   
echo "                     Information about the directory '$filename' "
echo " -----------------------------------------------------------------------"
echo "                              filetype: $filetype"
if [ "$system" = "Linux" ]; then
    echo "                           permissions: $symbolperms ($octalperms)"
else
	echo "                           permissions: $symbolperms"
fi
echo "              Number of subdirectories: $numsubdirs"
echo "                    Owner of directory: $username (uid=$uidnumeric)"
echo "                      File is in group: $groupname (gid=$gidnumeric)"
echo "         Directory's size in 1k blocks: $sizeblocks"

elif [ "$filetype_char" = "-" ]; then

echo " -----------------------------------------------------------------------"   
echo "                     Information about the file '$filename' "
echo " -----------------------------------------------------------------------"
echo "                              filetype: $filetype"
if [ "$system" = "Linux" ]; then
    echo "                           permissions: $symbolperms ($octalperms)"
else
	echo "                           permissions: $symbolperms"
fi
echo "                  Number of references: $links"
echo "                         Owner of file: $username (uid=$uidnumeric)"
echo "                      File is in group: $groupname (gid=$gidnumeric)"
echo "                  File's size in bytes: $sizebytes"
echo "              File's size in 1k blocks: $sizeblocks"

elif [ "$filetype_char" = "b" ] || [ "$filetype_char" = "c" ]; then

echo " -----------------------------------------------------------------------"   
echo "                     Information about the file '$filename' "
echo " -----------------------------------------------------------------------"
echo "                              filetype: $filetype"
if [ "$system" = "Linux" ]; then
    echo "                           permissions: $symbolperms ($octalperms)"
else
	echo "                           permissions: $symbolperms"
fi
echo "                  Number of references: $links"
echo "                         Owner of file: $username (uid=$uidnumeric)"
echo "                      File is in group: $groupname (gid=$gidnumeric)"
echo "                   Major device number: $majordevnum"
echo "                   Minor device number: $minordevnum"

else

echo " -----------------------------------------------------------------------"   
echo "                     Information about the file '$filename' "
echo " -----------------------------------------------------------------------"
echo "                              filetype: $filetype"
if [ "$system" = "Linux" ]; then
    echo "                           permissions: $symbolperms ($octalperms)"
else
	echo "                           permissions: $symbolperms"
fi
echo "                  Number of references: $links"
echo "                         Owner of file: $username (uid=$uidnumeric)"
echo "                      File is in group: $groupname (gid=$gidnumeric)"

fi
fi
}


#----------------------------------------------------------------------------
# the main program

# initialize our flag to indicate there have not been any errors
errors_seen=false

# Check the system we are on.
# Warn user that this script is only guaranteed for Linux and HP-UX.
system=`uname -s`
if [ "$system" != "Linux" ] && [ "$system" != "HP-UX" ]; then
	error WARNING! This script was only designed for Linux and HP-UX.
fi

# process the arguments
# if there's not at least one argument, it's a fatal error.
if [ $# -eq 0 ]; then
	fatal An OPTION is required to run this program.
fi

# the first argument MUST be a valid option. Checked in a special function.
checkArgs $1
shift

# If there was only one argument, function default_list generates the list
# of things to work on. 
# If there are more arguments, the list consists of the rest of the args. 
if [ $# -ge 1 ]; then
	list=$@
else
    # the function default_list outputs (to standard output)
    # a list of the default things to work on.
    list=$(default_list $system $mode)
fi

# Function dofile() is called for each item in list.
for item in $list; do
    dofile "$system" "$item"
done

# now simply exit with the exit status set depending on 
# whether errors were encountered or not
if [ "$errors_seen" = "true" ]; then
	exit 1
fi
exit 0